# NOTE: If you wanna use storage_limit, you need to ensure that:
#       - the overlay2 driver is being used
#       - your docker daemon is mounted in a xfs filesystem
#       - the filesystem have the pquota option enabled

services:
  vim:
    image: example
    build: /images/example

    stdin_open: true
    tty: true

    mem_limit: 100m     # 100MB
    cpus: 0.1           # 10% of a single core
    storage_opt:
      size: 150m        # 150MB

  bash:
    image: ubuntu:latest
    command: /bin/bash

    environment:
      - MY_VARIABLE=42

    volumes:
      - ./data:/mnt/data

    stdin_open: true
    tty: true

    mem_limit: 100m
    cpus: 0.1
    storage_opt:
      size: 150m        # 150MB
