# NOTE: If you wanna use storage_limit, you need to ensure that:
#       - the overlay2 driver is being used
#       - your docker daemon is mounted in a xfs filesystem
#       - the filesystem have the pquota option enabled

services:
  ls:
    image: ubuntu:latest
    command: /bin/ls -lh
    labels:
      permit_empty_passwords: true

  vim:
    image: example
    build: /images/example

    stdin_open: true
    tty: true


    deploy:
      resources:
        reservations:
          memory: 100Mb
          cpus: 0.1 # 10% of a single core

        limits:
          memory: 500Mb
          cpus: 0.5 # 50% of a single core

    storage_opt:
      size: 150Mb

    labels:
      #pam_auth: true
      password: "vipass"

  bash:
    image: ubuntu:latest
    command: /bin/bash

    environment:
      - MY_VARIABLE=42

    volumes:
      - ./data:/mnt/data

    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          memory: 100Mb
          cpus: 0.1 # 10% of a single core

        limits:
          memory: 500Mb
          cpus: 0.5 # 50% of a single core

    storage_opt:
      size: 150Mb

    labels:
      pam_auth: true


x-sshds:
  # This option only takes effect on services using the custom PAM module (the module provide us a way to identify
  # unique users without relying on ip addresses which isn't really accurate as several users can share the same ip)
  container_per_user: 2